//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfferManagement.BusinessModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfferManagement.BusinessModel.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ανώνυμη Εταιρεία - Α.Ε..
        /// </summary>
        internal static string enCompanyType_AE {
            get {
                return ResourceManager.GetString("enCompanyType_AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ανώνυμη Εταιρεία.
        /// </summary>
        internal static string enCompanyType_AE_Short {
            get {
                return ResourceManager.GetString("enCompanyType_AE_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ετερόρρυθμη Εταιρεία - Ε.Ε..
        /// </summary>
        internal static string enCompanyType_EE {
            get {
                return ResourceManager.GetString("enCompanyType_EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ετερόρρυθμη Εταιρεία.
        /// </summary>
        internal static string enCompanyType_EE_Short {
            get {
                return ResourceManager.GetString("enCompanyType_EE_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εταιρεία Περιορισμένης Ευθύνης - Ε.Π.Ε..
        /// </summary>
        internal static string enCompanyType_EPE {
            get {
                return ResourceManager.GetString("enCompanyType_EPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εταιρεία Περιορισμένης Ευθύνης.
        /// </summary>
        internal static string enCompanyType_EPE_Short {
            get {
                return ResourceManager.GetString("enCompanyType_EPE_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ιδιωτική Κεφαλαιουχική Εταιρεία - Ι.Κ.Ε..
        /// </summary>
        internal static string enCompanyType_IKE {
            get {
                return ResourceManager.GetString("enCompanyType_IKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ιδιωτική Κεφαλαιουχική Εταιρεία.
        /// </summary>
        internal static string enCompanyType_IKE_Short {
            get {
                return ResourceManager.GetString("enCompanyType_IKE_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ομόρρυθμη Εταιρεία - Ο.Ε..
        /// </summary>
        internal static string enCompanyType_OE {
            get {
                return ResourceManager.GetString("enCompanyType_OE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ομόρρυθμη Εταιρεία.
        /// </summary>
        internal static string enCompanyType_OE_Short {
            get {
                return ResourceManager.GetString("enCompanyType_OE_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ατομική Επιχείρηση.
        /// </summary>
        internal static string enCompanyType_PersonalCompany {
            get {
                return ResourceManager.GetString("enCompanyType_PersonalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προσαρμοσμένο Μήνυμα.
        /// </summary>
        internal static string enEmailType_CustomMessage {
            get {
                return ResourceManager.GetString("enEmailType_CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email με κωδικό πρόσβασης.
        /// </summary>
        internal static string enEmailType_ForgotPassword {
            get {
                return ResourceManager.GetString("enEmailType_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απάντηση σε ερώτημα του χρήστη.
        /// </summary>
        internal static string enEmailType_IncidentReportAnswer {
            get {
                return ResourceManager.GetString("enEmailType_IncidentReportAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πιστοποίηση Email Προμηθευτή.
        /// </summary>
        internal static string enEmailType_StoreEmailVerification {
            get {
                return ResourceManager.GetString("enEmailType_StoreEmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το IBAN δεν πρέπει να περιέχει κενά.
        /// </summary>
        internal static string enIBANValidationResult_ContainsSpaces {
            get {
                return ResourceManager.GetString("enIBANValidationResult_ContainsSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο IBAN δεν έχει αποδεκτό αναγνωριστικό χώρας.
        /// </summary>
        internal static string enIBANValidationResult_CountryCodeNotKnown {
            get {
                return ResourceManager.GetString("enIBANValidationResult_CountryCodeNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο IBAN είναι έγκυρος.
        /// </summary>
        internal static string enIBANValidationResult_IsValid {
            get {
                return ResourceManager.GetString("enIBANValidationResult_IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το IBAN της τράπεζας πρέπει να αποτελείται από  27 χαρακτήρες, χωρίς κενά και να αρχίζει από GR.
        /// </summary>
        internal static string enIBANValidationResult_NotGreekIBAN {
            get {
                return ResourceManager.GetString("enIBANValidationResult_NotGreekIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο IBAN δεν είναι έγκυρος.
        /// </summary>
        internal static string enIBANValidationResult_ValueFailsModule97Check {
            get {
                return ResourceManager.GetString("enIBANValidationResult_ValueFailsModule97Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν εισάγατε τιμή για τον IBAN.
        /// </summary>
        internal static string enIBANValidationResult_ValueMissing {
            get {
                return ResourceManager.GetString("enIBANValidationResult_ValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Οι χαρακτήρες του IBAN είναι περισσότεροι από το επιτρεπτό.
        /// </summary>
        internal static string enIBANValidationResult_ValueTooBig {
            get {
                return ResourceManager.GetString("enIBANValidationResult_ValueTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Οι χαρακτήρες του IBAN είναι λιγότεροι από το επιτρεπτό.
        /// </summary>
        internal static string enIBANValidationResult_ValueTooSmall {
            get {
                return ResourceManager.GetString("enIBANValidationResult_ValueTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αστυνομική Ταυτότητα.
        /// </summary>
        internal static string enIdentificationType_ID {
            get {
                return ResourceManager.GetString("enIdentificationType_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαβατήριο/Στρατιωτική Ταυτότητα.
        /// </summary>
        internal static string enIdentificationType_Passport {
            get {
                return ResourceManager.GetString("enIdentificationType_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ανθρακί.
        /// </summary>
        internal static string enLaptopColor_Anthracite {
            get {
                return ResourceManager.GetString("enLaptopColor_Anthracite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μαύρο.
        /// </summary>
        internal static string enLaptopColor_Black {
            get {
                return ResourceManager.GetString("enLaptopColor_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εγκεκριμένη.
        /// </summary>
        internal static string enOfferStatus_Approved {
            get {
                return ResourceManager.GetString("enOfferStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραμμένη.
        /// </summary>
        internal static string enOfferStatus_Deleted {
            get {
                return ResourceManager.GetString("enOfferStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε Επεξεργασία.
        /// </summary>
        internal static string enOfferStatus_InEdit {
            get {
                return ResourceManager.GetString("enOfferStatus_InEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απορριφθείσα.
        /// </summary>
        internal static string enOfferStatus_Rejected {
            get {
                return ResourceManager.GetString("enOfferStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υποβεβλημένη.
        /// </summary>
        internal static string enOfferStatus_Submitted {
            get {
                return ResourceManager.GetString("enOfferStatus_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε αξιολόγηση.
        /// </summary>
        internal static string enOfferStatus_UnderEvaluation {
            get {
                return ResourceManager.GetString("enOfferStatus_UnderEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποσυρμένη.
        /// </summary>
        internal static string enOfferStatus_Withdrawn {
            get {
                return ResourceManager.GetString("enOfferStatus_Withdrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δηλώθηκε από το Γραφείο Υποστήριξης Χρηστών.
        /// </summary>
        internal static string enReporterDeclarationType_FromHelpdesk {
            get {
                return ResourceManager.GetString("enReporterDeclarationType_FromHelpdesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δηλώθηκε μόνος του (από Portal).
        /// </summary>
        internal static string enReporterDeclarationType_FromPortal {
            get {
                return ResourceManager.GetString("enReporterDeclarationType_FromPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εγγεγραμμένος.
        /// </summary>
        internal static string enReporterDeclarationType_FromRegistration {
            get {
                return ResourceManager.GetString("enReporterDeclarationType_FromRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προμηθευτής.
        /// </summary>
        internal static string enReporterType_Store {
            get {
                return ResourceManager.GetString("enReporterType_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS με κωδικό πιστοποίησης.
        /// </summary>
        internal static string enSMSType_VerificationCode {
            get {
                return ResourceManager.GetString("enSMSType_VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν έχει υποβάλει αίτηση.
        /// </summary>
        internal static string enVerificationStatus_NoSubmittedRequest {
            get {
                return ResourceManager.GetString("enVerificationStatus_NoSubmittedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απορρίφθηκε.
        /// </summary>
        internal static string enVerificationStatus_Rejected {
            get {
                return ResourceManager.GetString("enVerificationStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Έχει υποβάλει αίτηση.
        /// </summary>
        internal static string enVerificationStatus_SubmittedRequest {
            get {
                return ResourceManager.GetString("enVerificationStatus_SubmittedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε διαδικασία αξιολόγησης.
        /// </summary>
        internal static string enVerificationStatus_UnderEvaluation {
            get {
                return ResourceManager.GetString("enVerificationStatus_UnderEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εγκρίθηκε.
        /// </summary>
        internal static string enVerificationStatus_Verified {
            get {
                return ResourceManager.GetString("enVerificationStatus_Verified", resourceCulture);
            }
        }
    }
}
