//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Διόρθωση Φωτογραφίας.
        /// </summary>
        internal static string UploadPhoto_CropImage {
            get {
                return ResourceManager.GetString("UploadPhoto_CropImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο τύπος της φωτογραφίας πρέπει να είναι .jpg.
        /// </summary>
        internal static string UploadPhoto_fileType {
            get {
                return ResourceManager.GetString("UploadPhoto_fileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η εικόνα πρέπει να έχει πλάτος και ύψος τουλάχιστον 240px.
        /// </summary>
        internal static string UploadPhoto_maxDimensions {
            get {
                return ResourceManager.GetString("UploadPhoto_maxDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το μέγιστο επιτρεπόμενο μέγεθος είναι 2ΜΒ.
        /// </summary>
        internal static string UploadPhoto_maxSize {
            get {
                return ResourceManager.GetString("UploadPhoto_maxSize", resourceCulture);
            }
        }
    }
}
