//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OfferInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OfferInput() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OfferInput", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο κωδικός της Προσφοράς στον Προμηθευτή. Μπορεί να αποτελείται μόνο από λατινικούς χαρακτήρες (μικρούς και κεφαλαίους), αριθμούς και τους ειδικούς χαρακτήρες (.-_/). Μέγιστο μήκος 60 χαρακτήρες..
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η περιγραφή της Προσφοράς [ελεύθερο κείμενο, μέχρι 500 χαρακτήρες].
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο τίτλος του Επεξεργαστή [ελεύθερο κείμενο, μέχρι 50 χαρακτήρες].
        /// </summary>
        internal static string Laptop_Cpu {
            get {
                return ResourceManager.GetString("Laptop_Cpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η ταχύτητα χρονισμού του επεξεργαστή σε GHz [τουλάχιστον 1.7Ghz].
        /// </summary>
        internal static string Laptop_CpuSpeed {
            get {
                return ResourceManager.GetString("Laptop_CpuSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η διάρκεια εγγύησης σε έτη (τουλάχιστον 2 έτη).
        /// </summary>
        internal static string Laptop_Guarantee {
            get {
                return ResourceManager.GetString("Laptop_Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Αριθμός θυρών Hdmi (τουλάχιστον 1).
        /// </summary>
        internal static string Laptop_HdmiCount {
            get {
                return ResourceManager.GetString("Laptop_HdmiCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο τίτλος του κατασκευαστή [ελεύθερο κείμενο, μέχρι 50 χαρακτήρες].
        /// </summary>
        internal static string Laptop_Manufacturer {
            get {
                return ResourceManager.GetString("Laptop_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to O τίτλος του μοντέλου [ελεύθερο κείμενο, μέχρι 50 χαρακτήρες].
        /// </summary>
        internal static string Laptop_Model {
            get {
                return ResourceManager.GetString("Laptop_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το URL της ιστοσελίδας του κατασκευαστή όπου παρουσιάζονται τα Official Specs της συσκευής [έγκυρη διεύθυνση ιστοσελίδας, π.χ. http://www.mypage.gr].
        /// </summary>
        internal static string Laptop_OfficialSpecsUrl {
            get {
                return ResourceManager.GetString("Laptop_OfficialSpecsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο τίτλος και η έκδοση του λειτουργικού συστήματος [ελεύθερο κείμενο, μέχρι 100 χαρακτήρες].
        /// </summary>
        internal static string Laptop_OperatingSystem {
            get {
                return ResourceManager.GetString("Laptop_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο αριθμός των πυρήνων του επεξεργαστή (τουλάχιστον 2 πυρήνες).
        /// </summary>
        internal static string Laptop_ProcessorCoreCount {
            get {
                return ResourceManager.GetString("Laptop_ProcessorCoreCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η χωρητικότητα της Μνήμης RAM σε GB (τουλάχιστον 4GB).
        /// </summary>
        internal static string Laptop_RamSize {
            get {
                return ResourceManager.GetString("Laptop_RamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ανάλυση οθόνης: πλάτος (&gt;= 1366).
        /// </summary>
        internal static string Laptop_ScreenResolutionX {
            get {
                return ResourceManager.GetString("Laptop_ScreenResolutionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ανάλυση οθόνης: ύψος(&gt;= 768).
        /// </summary>
        internal static string Laptop_ScreenResolutionY {
            get {
                return ResourceManager.GetString("Laptop_ScreenResolutionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η διαγώνιος της οθόνης σε ίντσες (τουλάχιστον 15.6&quot;).
        /// </summary>
        internal static string Laptop_ScreenSize {
            get {
                return ResourceManager.GetString("Laptop_ScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η χωρητικότητα του HDD δίσκου σε GB (τουλάχιστον 500 GB).
        /// </summary>
        internal static string Laptop_StorageSize {
            get {
                return ResourceManager.GetString("Laptop_StorageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η χωρητικότητα του SSD δίσκου σε GB (τουλάχιστον 128 GB).
        /// </summary>
        internal static string Laptop_StorageSizeSSD {
            get {
                return ResourceManager.GetString("Laptop_StorageSizeSSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Αριθμός θυρών USB (τουλάχιστον 3).
        /// </summary>
        internal static string Laptop_UsbCount {
            get {
                return ResourceManager.GetString("Laptop_UsbCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το URL της ιστοσελίδας του Προμηθευτή όπου παρουσιάζεται αναλυτική περιγραφή της Προσφοράς [έγκυρη διεύθυνση ιστοσελίδας, π.χ. http://www.mypage.gr].
        /// </summary>
        internal static string OfferUrl {
            get {
                return ResourceManager.GetString("OfferUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η τιμή της προσφοράς σε ευρώ (συμπεριλαμβανομένου ΦΠΑ).
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο τίτλος της Προσφοράς [ελεύθερο κείμενο, μέχρι 100 χαρακτήρες].
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
