//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderInput() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OrderInput", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο Αριθμός Πρακτικού του Διοικητικού Συμβουλίου.
        /// </summary>
        internal static string BoardProtocolNumber {
            get {
                return ResourceManager.GetString("BoardProtocolNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η Τοποθεσία Υπογραφής του Ιδιωτικού Συμφωνητικού.
        /// </summary>
        internal static string ContractSigningAddress {
            get {
                return ResourceManager.GetString("ContractSigningAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η Θέση του Νομίμου Εκπροσώπου στην Εταιρεία στην αιτιατική κλίση ώστε να συμπληρωθεί στην Σύμβαση [πχ. Πρόεδρο ή Αναπληρωτή Πρόεδρο].
        /// </summary>
        internal static string LegalPersonCompanyPosition {
            get {
                return ResourceManager.GetString("LegalPersonCompanyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η τιμή πώλησης της προσφοράς σε ευρώ (συμπεριλαμβανομένου ΦΠΑ).
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο σειριακός αριθμός του laptop/netbook/tablet.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το Ον/μο του Υπογράφοντα στην αιτιατική κλίση ώστε να συμπληρωθεί στην Σύμβαση [π.χ. ΓΕΩΡΓΙΟ ΑΝΤΩΝΙΑΔΗ].
        /// </summary>
        internal static string SigningPersonName {
            get {
                return ResourceManager.GetString("SigningPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο κωδικός του Φοιτητή.
        /// </summary>
        internal static string StudentCode {
            get {
                return ResourceManager.GetString("StudentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο αριθμός Δελτίου Ταυτότητας του Φοιτητή.
        /// </summary>
        internal static string StudentIdentificationCardNumber {
            get {
                return ResourceManager.GetString("StudentIdentificationCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο 12-ψήφιος Κωδικός του Κουπονιού του Φοιτητή [Γίνεται έλεγχος εγκυρότητας του Κωδικού].
        /// </summary>
        internal static string VoucherCode {
            get {
                return ResourceManager.GetString("VoucherCode", resourceCulture);
            }
        }
    }
}
