//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegistrationInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationInput() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RegistrationInput", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to [έγκυρο email, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Προσοχή: Στο email που θα δηλώσετε, θα σας σταλεί το email ενεργοποίησης του λογαριασμού σας. Βεβαιωθείτε ότι το πληκτρολογήσατε σωστά..
        /// </summary>
        internal static string EmailInfo {
            get {
                return ResourceManager.GetString("EmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το κινητό πρέπει να ξεκινάει από 69 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό.
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο Κωδικός Πρόσβασης πρέπει να αποτελείται από τουλάχιστον 8 χαρακτήρες, εκ των οποίων τουλάχιστον ένας να είναι αριθμητικός (0-9) και ένας ειδικός (!@#$%^&amp;*). Επιτρέπονται μόνο λατινικοί, αριθμητικοί και οι παραπάνω ειδικοί χαρακτήρες..
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  Για τη δική σας ασφάλεια συνιστούμε να επιλέξετε έναν συνδυασμό από γράμματα, αριθμούς ή σύμβολα για να δημιουργήσετε έναν μοναδικό κωδικό πρόσβασης που δεν σχετίζεται με τα προσωπικά σας στοιχεία. Ή, επιλέξτε μια τυχαία λέξη ή φράση και εισαγάγετε λέξεις και αριθμούς στην αρχή, στη μέση και στο τέλος, για να είναι ακόμα πιο δύσκολο να τη μαντέψει κανείς (για παράδειγμα &quot;m1awra1ap3tal0uda&quot;). Η χρήση απλών λέξεων ή φράσεων όπως &quot;password&quot; ή &quot;letmein&quot;, οι ακολουθίες πλήκτρων όπως &quot;qwerty&quot; ή &quot;qazwsx&quot; ή οι ακολ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordInfo {
            get {
                return ResourceManager.GetString("PasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Επιτρέπονται μόνο λατινικοί χαρακτήρες, αριθμητικοί (π.χ. 1,2,3) ή ειδικοί (_, - και .) [τουλάχιστον 5 χαρακτήρες].
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
