//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoreInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreInput() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StoreInput", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το Α.Φ.Μ του Προμηθευτή [Γίνεται έλεγχος εγκυρότητας του ΑΦΜ].
        /// </summary>
        internal static string AFM {
            get {
                return ResourceManager.GetString("AFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το e-mail του Αναπληρωτή Υπευθύνου του Προμηθευτή για τη δράση [έγκυρο e-mail, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string AlternateContactEmail {
            get {
                return ResourceManager.GetString("AlternateContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το κινητό τηλέφωνο του Αναπληρωτή Υπευθύνου του Προμηθευτή για τη δράση [πρέπει να ξεκινάει από 69 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string AlternateContactMobilePhone {
            get {
                return ResourceManager.GetString("AlternateContactMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το Ον/μο του Αναπληρωτή Υπευθύνου του Προμηθευτή για τη δράση  [ελεύθερο κείμενο, μέχρι 100 χαρακτήρες].
        /// </summary>
        internal static string AlternateContactName {
            get {
                return ResourceManager.GetString("AlternateContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το σταθερό τηλέφωνο του Αναπληρωτή Υπευθύνου του Προμηθευτή για τη δράση [πρέπει να ξεκινάει από 2 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string AlternateContactPhone {
            get {
                return ResourceManager.GetString("AlternateContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το e-mail του Υπευθύνου του Προμηθευτή για τη δράση [έγκυρο e-mail, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το κινητό τηλέφωνο του Υπευθύνου του Προμηθευτή για τη δράση [πρέπει να ξεκινάει από 69 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string ContactMobilePhone {
            get {
                return ResourceManager.GetString("ContactMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το Ον/μο του Υπευθύνου του Προμηθευτή για τη δράση  [ελεύθερο κείμενο, μέχρι 100 χαρακτήρες].
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το σταθερό τηλέφωνο του Υπευθύνου του Προμηθευτή για τη δράση [πρέπει να ξεκινάει από 2 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το e-mail του Νομίμου Εκπροσώπου του Προμηθευτή [έγκυρο e-mail, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string LegalPersonEmail {
            get {
                return ResourceManager.GetString("LegalPersonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το Ον/μο του Νομίμου Εκπροσώπου του Προμηθευτή [ελεύθερο κείμενο, μέχρι 100 χαρακτήρες].
        /// </summary>
        internal static string LegalPersonName {
            get {
                return ResourceManager.GetString("LegalPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το τηλέφωνο του Νομίμου Εκπροσώπου του Προμηθευτή [πρέπει να αποτελείται από ακριβώς 10 αριθμητικούς χαρακτήρες και να ξεκινάει από 2 (αν πρόκειται για σταθερό) ή από 69 (αν πρόκειται για κινητό)].
        /// </summary>
        internal static string LegalPersonPhone {
            get {
                return ResourceManager.GetString("LegalPersonPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Η πλήρης επωνυμία του Προμηθευτή [ελεύθερο κείμενο, μέχρι 500 χαρακτήρες].
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το e-mail επικοινωνίας με τον Προμηθευτή[έγκυρο e-mail, π.χ. myaccount@myisp.gr ].
        /// </summary>
        internal static string StoreEmail {
            get {
                return ResourceManager.GetString("StoreEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το Fax επικοινωνίας με τον Προμηθευτή [πρέπει να ξεκινάει από 2 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string StoreFax {
            get {
                return ResourceManager.GetString("StoreFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το κινητό τηλέφωνο επικοινωνίας με τον Προμηθευτή [πρέπει να ξεκινάει από 69 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string StoreMobilePhone {
            get {
                return ResourceManager.GetString("StoreMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το σταθερό τηλέφωνο επικοινωνίας με τον Προμηθευτή [πρέπει να ξεκινάει από 2 ή 800 ή 801 και να αποτελείται από 10 αριθμητικούς χαρακτήρες ή να είναι πενταψήφιο ή τετραψήφιο νούμερο, χωρίς κενά].
        /// </summary>
        internal static string StorePhone {
            get {
                return ResourceManager.GetString("StorePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το URL της ιστοσελίδας του Προμηθευτή [έγκυρη διεύθυνση ιστοσελίδας, π.χ. http://www.mypage.gr].
        /// </summary>
        internal static string StoreURL {
            get {
                return ResourceManager.GetString("StoreURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο Διακριτικός Τίτλος του Προμηθευτή [ελεύθερο κείμενο, μέχρι 500 χαρακτήρες].
        /// </summary>
        internal static string TradeName {
            get {
                return ResourceManager.GetString("TradeName", resourceCulture);
            }
        }
    }
}
