//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoreUserInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreUserInput() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StoreUserInput", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το Ον/μο του Χρήστη [ελεύθερο κείμενο, μέχρι 50 χαρακτήρες].
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Το σταθερό τηλέφωνο του Χρήστη [πρέπει να ξεκινάει από 2 και να αποτελείται από 10 αριθμητικούς χαρακτήρες, χωρίς κενό].
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο Χρήστης θα έχει το δικαίωμα Διαχείρισης των Franchisee.
        /// </summary>
        internal static string FranchiseesManager {
            get {
                return ResourceManager.GetString("FranchiseesManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο Χρήστης θα έχει το δικαίωμα Δημιουργίας και Διαχείρισης Προσφορών.
        /// </summary>
        internal static string OffersManager {
            get {
                return ResourceManager.GetString("OffersManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο Χρήστης θα έχει το δικαίωμα Δημιουργίας και Διαχείρισης Παραγγελιών.
        /// </summary>
        internal static string OrdersManager {
            get {
                return ResourceManager.GetString("OrdersManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ο Χρήστης θα έχει το δικαίωμα Δημιουργίας και Διαχείρισης Υποκαταστημάτων.
        /// </summary>
        internal static string SubStoresManager {
            get {
                return ResourceManager.GetString("SubStoresManager", resourceCulture);
            }
        }
    }
}
